// <auto-generated />
using System;
using Diva.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diva.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DivaDbContext))]
    [Migration("20260515060000_AddUserPreferencesAndMemoryUserId")]
    partial class AddUserPreferencesAndMemoryUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            // Full model snapshot is maintained in DivaDbContextModelSnapshot.cs.
            // This Designer.cs only needs the [Migration] attribute for EF discovery.
            // EF Core uses the snapshot for the current model state.
#pragma warning restore 612, 618
        }
    }
}
